name: Stream merge
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the source topic
    defaultValue: image-processed
    required: true
  - name: output
    inputType: OutputTopic
    description: Name of the destination topic
    defaultValue: image-processed-merged
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
