name: TFL Camera Feed
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for TfL camera images
    defaultValue: tfl-cameras
    required: true
  - name: sleep_interval
    inputType: FreeText
    description: ''
    defaultValue: 60
    required: true
  - name: tfl_api_key
    inputType: Secret
    description: ''
    defaultValue: tfl_api_key
    required: true
  - name: new_var
    inputType: Secret
    description: ''
    defaultValue: new_secret
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
