name: TFL Camera Feed
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for TfL camera images
    defaultValue: tfl-cameras
    required: true
  - name: api_key
    inputType: HiddenText
    description: Your TfL API Key
    defaultValue: ba4f0a6e85ce4e02b8ae2864f9147beb
    required: true
  - name: api_key
    inputType: Secret
    description: ''
    defaultValue: api_key
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
