name: TFL Camera Feed
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for TfL camera images
    defaultValue: tfl-cameras
    required: true
  - name: api_key
    inputType: Secret
    description: ''
    defaultValue: camera_api_key
    required: false
  - name: topics
    inputType: InputTopic
    description: ''
    defaultValue: ''
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
