name: Hotspot Service
language: python
variables:
  - name: input
    inputType: InputTopic
    description: ''
    defaultValue: image-processed
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
