name: TotalVehicles
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: image-processed2
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: image-vehicles
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
