name: Geofence
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: tfl-cameras
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: fenced-cameras
    required: true
  - name: fence_coordinates
    inputType: FreeText
    description: ''
    defaultValue: '[(-0.1203346,51.5417444),(-0.0411987,51.5404633),(-0.0411987,51.5007287),(-0.1253128,51.4966678),(-0.1205063,51.5417444)]'
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
