name: TfL image processing UI
language: nodejs
variables:
  - name: processed
    inputType: InputTopic
    description: The topic to read from
    defaultValue: image-processed
    required: true
  - name: uiProjectDeploymentId
    inputType: Secret
    description: ''
    defaultValue: uiProjectDeploymentId
    required: false
  - name: computerVisionProjectDeploymentId
    inputType: Secret
    description: ''
    defaultValue: computerVisionProjectDeploymentId
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
