name: Data API
language: python
variables:
  - name: buffered_stream
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: buffered-data
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
