name: Data API
language: python
variables:
  - name: buffered_stream
    inputType: InputTopic
    description: The output from the Image Processing stage
    defaultValue: buffered-data
    required: false
  - name: sdfsdfsdf
    inputType: InputTopic
    description: ''
    defaultValue: buffered-data
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
