name: Data API
language: python
variables:
  - name: objects
    inputType: InputTopic
    description: The output from the Image Processing stage
    defaultValue: image-processed
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
