name: Data Buffer
language: python
variables:
  - name: max_vehicles
    inputType: InputTopic
    description: ''
    defaultValue: max-vehicles
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
